name: flutter_app_remote_stayhome
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  intl: ^0.17.0 # Add this line
  # the device_preview is show screem on size
  device_preview: ^1.1.0
  equatable: ^2.0.3
  # add nar_bar
  google_nav_bar: ^5.0.6
  # oktoast: ^3.2.0
  # uuid: 3.0.6
  #connet mysql
  mysql1: ^0.20.0
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_storage: ^10.3.4
  #provider
  provider: ^6.0.3

  #add image in project
  image_picker: ^0.8.5+3
  # image_picker_web: ^2.1.1
  # icon
  line_icons: ^2.0.0
  flutter_svg: ^0.22.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
