// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQcsxGz0syqhBX5TFN6Yw86H8CIQ_juU',
    appId: '1:180774913918:web:ac020a020c818f1538152f',
    messagingSenderId: '180774913918',
    projectId: 'flutter-app-homestay',
    authDomain: 'flutter-app-homestay.firebaseapp.com',
    storageBucket: 'flutter-app-homestay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByI-WvRj6N-F6oyr2feKn-WkKFB6_JZmU',
    appId: '1:180774913918:android:225bcb3c06925d4438152f',
    messagingSenderId: '180774913918',
    projectId: 'flutter-app-homestay',
    storageBucket: 'flutter-app-homestay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eKBzQCWTGhMTgd_CjepT1FeMz4t2Pog',
    appId: '1:180774913918:ios:43bd335951f894d338152f',
    messagingSenderId: '180774913918',
    projectId: 'flutter-app-homestay',
    storageBucket: 'flutter-app-homestay.appspot.com',
    iosClientId: '180774913918-68gr5rngdeb9ln8tic2dsckqton1420c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppRemoteStayhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4eKBzQCWTGhMTgd_CjepT1FeMz4t2Pog',
    appId: '1:180774913918:ios:43bd335951f894d338152f',
    messagingSenderId: '180774913918',
    projectId: 'flutter-app-homestay',
    storageBucket: 'flutter-app-homestay.appspot.com',
    iosClientId: '180774913918-68gr5rngdeb9ln8tic2dsckqton1420c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppRemoteStayhome',
  );
}
